// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3IpLHA-KOBkVpBL7bHP0RwxwN_DOGoA',
    appId: '1:321578774200:web:a62b3a2ad2e0355e21ce4d',
    messagingSenderId: '321578774200',
    projectId: 'grouppocket-402df',
    authDomain: 'grouppocket-402df.firebaseapp.com',
    storageBucket: 'grouppocket-402df.firebasestorage.app',
    measurementId: 'G-34MYJBFRM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3IpLHA-KOBkVpBL7bHP0RwxwN_DOGoA',
    appId: '1:321578774200:android:your_android_app_id',
    messagingSenderId: '321578774200',
    projectId: 'grouppocket-402df',
    storageBucket: 'grouppocket-402df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe3IpLHA-KOBkVpBL7bHP0RwxwN_DOGoA',
    appId: '1:321578774200:ios:your_ios_app_id',
    messagingSenderId: '321578774200',
    projectId: 'grouppocket-402df',
    storageBucket: 'grouppocket-402df.firebasestorage.app',
    iosBundleId: 'com.example.grouppocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe3IpLHA-KOBkVpBL7bHP0RwxwN_DOGoA',
    appId: '1:321578774200:ios:your_macos_app_id',
    messagingSenderId: '321578774200',
    projectId: 'grouppocket-402df',
    storageBucket: 'grouppocket-402df.firebasestorage.app',
    iosBundleId: 'com.example.grouppocket',
  );
}
